Save a debug of factory.sh
(cherry picked from commit 3b75aa352f7812ab196a6d005c5c7e702f5bb321)

diff --git a/usr.sbin/bsdinstall/scripts/auto b/usr.sbin/bsdinstall/scripts/auto
--- a/usr.sbin/bsdinstall/scripts/auto
+++ b/usr.sbin/bsdinstall/scripts/auto
@@ -393,7 +393,8 @@ if [ -n "${mounted_nullfs}" ]; then
 fi
 
 if [ -f /root/factory.sh ]; then
-	sh /root/factory.sh || error "System configuration failed"
+	sh -x /root/factory.sh 2>/tmp/factory.debug \
+	    || error "System configuration failed"
 fi
 #bsdinstall rootpass || error "Could not set root password"
 
