Execute /root/factory.sh if it's present

diff --git a/usr.sbin/bsdinstall/scripts/auto b/usr.sbin/bsdinstall/scripts/auto
--- a/usr.sbin/bsdinstall/scripts/auto
+++ b/usr.sbin/bsdinstall/scripts/auto
@@ -379,6 +379,9 @@ fi
 
 bsdinstall checksum || error "Distribution checksum failed"
 bsdinstall distextract || error "Distribution extract failed"
+if [ -f /root/factory.sh ]; then
+	sh /root/factory.sh || error "System configuration failed"
+fi
 #bsdinstall rootpass || error "Could not set root password"
 
 trap true SIGINT	# This section is optional
