Umount distdir after use
(cherry picked from commit 191ef96861e4086e5dd8f267a10ec1d5b6bdad9d)

diff --git a/usr.sbin/bsdinstall/scripts/auto b/usr.sbin/bsdinstall/scripts/auto
--- a/usr.sbin/bsdinstall/scripts/auto
+++ b/usr.sbin/bsdinstall/scripts/auto
@@ -305,6 +305,7 @@ case "$PARTMODE" in
 	;;
 esac
 
+unset mounted_nullfs
 if [ ! -z "$FETCH_DISTRIBUTIONS" ]; then
 	ALL_DISTRIBUTIONS="$DISTRIBUTIONS"
 	WANT_DEBUG=
@@ -318,6 +319,7 @@ if [ ! -z "$FETCH_DISTRIBUTIONS" ]; then
 	if [ -d $BSDINSTALL_DISTDIR ]; then
 		DISTDIR_IS_UNIONFS=1
 		mount_nullfs -o union "$BSDINSTALL_FETCHDEST" "$BSDINSTALL_DISTDIR"
+		mounted_nullfs=1
 	else
 		export DISTRIBUTIONS="$FETCH_DISTRIBUTIONS"
 		export BSDINSTALL_DISTDIR="$BSDINSTALL_FETCHDEST"
@@ -370,6 +372,7 @@ if [ ! -z "$LOCAL_DISTRIBUTIONS" ]; then
 	if [ -d $BSDINSTALL_DISTDIR ]; then
 		DISTDIR_IS_UNIONFS=1
 		mount_nullfs -o union "$BSDINSTALL_FETCHDEST" "$BSDINSTALL_DISTDIR"
+		mounted_nullfs=1
 		export BSDINSTALL_DISTDIR="$BSDINSTALL_FETCHDEST"
 	fi
 	env DISTRIBUTIONS="$LOCAL_DISTRIBUTIONS" \
@@ -384,6 +387,13 @@ bsdinstall distextract || error "Distribution extract failed"
 # Set up boot loader
 bsdinstall bootconfig || error "Failed to configure bootloader"
 
+if [ -n "${mounted_nullfs}" ]; then
+	umount $BSDINSTALL_DISTDIR
+fi
+
+if [ -f /root/factory.sh ]; then
+	sh /root/factory.sh || error "System configuration failed"
+fi
 #bsdinstall rootpass || error "Could not set root password"
 
 trap true SIGINT	# This section is optional
